[build]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF apps/weather-app pnpm-lock.yaml pnpm-workspace.yaml"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  command = "pnpm run dev"
  targetPort = 5173
  port = 8888
  autoLaunch = false
